### ISSUE TITLE
MUSE cubes header 

### ISSUE THREAD

**Issue by margarita-luna** [kateharborne/SimSpin-post-process#1]
The code works on cubes made with SAMI, but not with MUSE: the header keyword CDELT3 is CD3_3 for MUSE cubes so the function apply_pPXF does not recognise SimSpin outputs made using MUSE as a telescope.

**Comment by kateharborne** [comment]
Great spot @margarita-luna! I've not re-visited this code since I wrote it and the [`write_simspin_FITS`](https://github.com/kateharborne/SimSpin/blob/master/R/write_simspin_FITS.R) function has changed a bit since the original version! 

I've opened a new branch on the SimSpin repository [here](https://github.com/kateharborne/SimSpin/tree/dev-FITSheader). I have also [opened this as an issue on the main SimSpin repo](https://github.com/kateharborne/SimSpin/issues/22) and will update the code. 

I seem to have renamed the parameters in the header for the cube element in HDU 2... The original names make more sense so I will return the header keyword to CDELT3 rather than CD3_3. (I can't remember why this changed... so I'm guessing it was simply an oversight!)

Hopefully this should fix the compatability issue. 

I'll close this issue once the fix has been pushed to the main SimSpin repo.

**Comment by kateharborne** [comment]
Fix has now been pushed and merged with the main branch [here](https://github.com/kateharborne/SimSpin/pull/23). @margarita-luna - you should be able to pull these updates to your SimSpin version and new cubes will hopefuly work with this pPXF fitting code.
